apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.3
spec:
  bai_configuration:
    business_performance_center:
      all_users_access: true
    image_credentials:
      registry: cp.icr.io/cp/cp4a
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 21.0.3-IF009
  ecm_configuration:
    cmis:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cmis
        tag: 21.0.3-IF009
    cpe:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: 21.0.3-IF009
    css:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/css
        tag: 21.0.3-IF009
    document_processing:
      cdra:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/cdra
          tag: 21.0.3-IF009
      cds:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/cds
          tag: 21.0.3-IF009
      cpds:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/cpds
          tag: 21.0.3-IF009
      gitgateway:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/gitgateway
          tag: 21.0.3-IF009
      mongo:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/mongo
          tag: 4.2.17
      viewone:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/viewone
          tag: 21.0.3-IF009
    graphql:
      graphql_production_setting:
        enable_graph_iql: true
      image:
        repository: cp.icr.io/cp/cp4a/fncm/graphql
        tag: 21.0.3-IF009
    tm:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/taskmgr
        tag: 21.0.3-IF009
  ads_configuration:
    run_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-run
        tag: 21.0.3-IF009
    parsing_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-parsing
        tag: 21.0.3-IF009
    git_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-gitservice
        tag: 21.0.3-IF009
    front:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-front
        tag: 21.0.3-IF009
    decision_runtime_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-runtime
        tag: 21.0.3-IF009
    decision_designer:
      enabled: true
    embedded_build_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-build
        tag: 21.0.3-IF009
    rest_api:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-restapi
        tag: 21.0.3-IF009
    credentials_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-credentials
        tag: 21.0.3-IF009
    rr_integration:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-rrintegration
        tag: 21.0.3-IF009
    decision_runtime:
      enabled: true
    download_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-download
        tag: 21.0.3-IF009
  bastudio_configuration:
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 21.0.3-IF009
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 21.0.3-IF009
    playback_server:
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 21.0.3-IF009
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 21.0.3-IF009
  ier_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ier/ier
      tag: 21.0.3-IF009
  workflow_authoring_configuration:
    bas_auto_import_job:
      repository: cp.icr.io/cp/cp4a/baw/toolkit-installer
      tag: 21.0.3-IF009
    case:
      init_job_image:
        repository: cp.icr.io/cp/cp4a/baw/workflow-server-case-initialization
        tag: 21.0.3-IF009
    content_integration:
      init_job_image:
        repository: cp.icr.io/cp/cp4a/baw/iaws-ps-content-integration
        tag: 21.0.3-IF009
    ibm_workplace_job:
      repository: cp.icr.io/cp/cp4a/baw/iaws-ibm-workplace
      tag: 21.0.3-IF009
    image:
      repository: cp.icr.io/cp/cp4a/bas/workflow-authoring
      tag: 21.0.3-IF009
    jms:
      image:
        repository: cp.icr.io/cp/cp4a/baw/jms
        tag: 21.0.3-IF009
    pfs_bpd_database_init_job:
      repository: cp.icr.io/cp/cp4a/baw/pfs-bpd-database-init-prod
      tag: 21.0.3-IF009
    upgrade_job:
      repository: cp.icr.io/cp/cp4a/baw/workflow-server-dbhandling
      tag: 21.0.3-IF009
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator
      tag: 21.0.3-IF009
  odm_configuration:
    decisionCenter:
      enabled: true
    decisionRunner:
      enabled: true
    decisionServerRuntime:
      enabled: true
    image:
      pullSecrets: admin.registrykey
      repository: cp.icr.io/cp/cp4a/odm
  pfs_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/baw/pfs-prod
      tag: 21.0.3-IF009
  baml_configuration:
    intelligent_task_prioritization:
      image:
        repository: cp.icr.io/cp/cp4a/baw/bui-task-prioritization
        tag: 21.0.3-IF009
    workforce_insights:
      image:
        repository: cp.icr.io/cp/cp4a/baw/workforce-insights
        tag: 21.0.3-IF009
  ca_configuration:
    deeplearning:
      gpu_enabled: false
      nodelabel_key: null
      nodelabel_value: null
    global:
      image:
        repository: cp.icr.io/cp/cp4a/iadp
        tag: 21.0.3-IF009
  ibm_license: accept
  appVersion: 21.0.3
  shared_configuration:
    sc_cpe_limited_storage: false
    sc_deployment_type: Production
    sc_optional_components: >-
      ads_designer,ads_runtime,bai,baml,ban,baw_authoring,business_orchestration,case,cmis,content_integration,css,decisionCenter,decisionRunner,decisionServerRuntime,document_processing_designer,ier,pfs,tm,workstreams
    image_pull_secrets:
      - admin.registrykey
    trusted_certificate_list:
      - discover-baw
    sc_deployment_patterns: >-
      foundation,application,content,decisions,decisions_ads,document_processing,workflow-workstreams
    sc_deployment_baw_license: non-production
    storage_configuration:
      sc_block_storage_classname: ibmc-block-gold
      sc_dynamic_storage_classname: managed-nfs-storage
      sc_fast_file_storage_classname: managed-nfs-storage
      sc_medium_file_storage_classname: managed-nfs-storage
      sc_slow_file_storage_classname: managed-nfs-storage
    root_ca_secret: '{{ meta.name }}-root-ca'
    sc_run_as_user: null
    sc_content_initialization: true
    sc_deployment_license: non-production
    images:
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 21.0.3-IF009
      gitea:
        repository: cp.icr.io/cp/cp4a/demo/gitea
        tag: 1.15.8
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 21.0.3-IF009
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 21.0.3-IF009
      openldap:
        repository: cp.icr.io/cp/cp4a/demo/openldap
        tag: 1.5.0
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 21.0.3-IF009
    sc_ingress_enable: false
    sc_image_repository: cp.icr.io
    sc_deployment_platform: ROKS
    sc_deployment_fncm_license: non-production